import { configApp, INCLUDE_LIST } from '@adonisjs/eslint-config'

export default configApp(
  {
    name: 'Ignore generated files',
    // "This file is automatically generated / DO NOT EDIT manually" —
    // regenerated by `node ace migration:run`'s indexEntities hook, whose
    // own array-wrapping doesn't match prettier's, so linting it just
    // churns every time migrations run (e.g. in CI).
    ignores: ['database/schema.ts'],
  },
  {
    name: 'Project overrides',
    files: INCLUDE_LIST,
    rules: {
      // This codebase's naming convention is dotted kebab-case
      // (`create-product.use-case.ts`, `product-repository.interface.ts`,
      // `household.aggregate.ts`) throughout src/domain, src/application,
      // src/infrastructure, src/presentation — not the config's default
      // snake_case.
      '@unicorn/filename-case': 'off',
    },
  },
)
