import '#presentation/health.routes'
import '#presentation/identity/auth.routes'
import '#presentation/identity/household.routes'
import '#presentation/settings/ai-settings.routes'
import '#presentation/fridge/product.routes'
import '#presentation/receipt/receipt.routes'
import '#presentation/shopping-list/shopping-item.routes'
import '#presentation/recipe/recipe.routes'
