/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountSchema extends BaseModel {
  static $columns = ['accessToken', 'accessTokenExpiresAt', 'accountId', 'createdAt', 'id', 'idToken', 'issuer', 'password', 'providerId', 'refreshToken', 'refreshTokenExpiresAt', 'scope', 'updatedAt', 'userId'] as const
  $columns = AccountSchema.$columns
  @column()
  declare accessToken: string | null
  @column.dateTime()
  declare accessTokenExpiresAt: DateTime | null
  @column()
  declare accountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare idToken: string | null
  @column()
  declare issuer: string
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare providerId: string
  @column()
  declare refreshToken: string | null
  @column.dateTime()
  declare refreshTokenExpiresAt: DateTime | null
  @column()
  declare scope: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class AiProviderSettingSchema extends BaseModel {
  static $columns = ['activeProvider', 'id', 'updatedAt', 'updatedBy'] as const
  $columns = AiProviderSettingSchema.$columns
  @column()
  declare activeProvider: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
}

export class HouseholdSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'inviteCode', 'name', 'ownerId', 'updatedAt'] as const
  $columns = HouseholdSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare inviteCode: string
  @column()
  declare name: string
  @column()
  declare ownerId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class HouseholdMemberSchema extends BaseModel {
  static $columns = ['householdId', 'id', 'joinedAt', 'role', 'userId'] as const
  $columns = HouseholdMemberSchema.$columns
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare joinedAt: DateTime
  @column()
  declare role: string
  @column()
  declare userId: string
}

export class ProductSchema extends BaseModel {
  static $columns = ['categories', 'category', 'createdAt', 'expiresAt', 'householdId', 'id', 'imageKey', 'location', 'name', 'openedAt', 'openfoodfactId', 'price', 'quantity', 'receiptId', 'unit', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column()
  declare categories: any | null
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageKey: string | null
  @column()
  declare location: string
  @column()
  declare name: string
  @column.dateTime()
  declare openedAt: DateTime | null
  @column()
  declare openfoodfactId: string | null
  @column()
  declare price: string | null
  @column()
  declare quantity: number
  @column()
  declare receiptId: string | null
  @column()
  declare unit: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ReceiptSchema extends BaseModel {
  static $columns = ['createdAt', 'householdId', 'id', 'imageKey', 'itemsCount', 'scannedAt', 'storeName', 'totalAmount', 'updatedAt'] as const
  $columns = ReceiptSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageKey: string | null
  @column()
  declare itemsCount: number
  @column.dateTime()
  declare scannedAt: DateTime
  @column()
  declare storeName: string
  @column()
  declare totalAmount: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SessionSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'ipAddress', 'token', 'updatedAt', 'userAgent', 'userId'] as const
  $columns = SessionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'emailVerified', 'id', 'image', 'name', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare emailVerified: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare image: string | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class VerificationSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'identifier', 'updatedAt', 'value'] as const
  $columns = VerificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare identifier: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare value: string
}
